### ISSUE TITLE
Number variable reset at new request and search slot type

### ISSUE THREAD

**Issue by SoulofAkuma** [andrewstech/youtube-alexa-edition#11]
I have two bugs and two fixes.
1. The "number" variable (the one which controls which search result is picked and played) does not reset when I start a new Intent
2. The search query does only recognize one word (with your version I was able to play songs with a one-word name)

Here are the fixes I suggest:
1. Whenever the intent "music" is triggered, just set number to 0 when you set preview to 1.
2. Change the slot type of "search" to "Search Query" so that it takes the literal string and puts it into the web request (I removed the custom data types from the intent and it worked fine for me after I uploaded it despite an error message. There may be other problems originating from that, however, there is no way around changing the type if you want the search query to be recognized properly)

I am using project version 4 (it is the one Paul Hibbert has in his description). If there is already a new version fixing these issues, don't mind me.

**Comment by andrewstech** [comment]
Thank-you for telling me about this. I will have a look at integrating this.
