### ISSUE TITLE
Voiceflow in V3 looks different and does not process

### ISSUE THREAD

**Issue by narfel** [andrewstech/youtube-alexa-edition#12]
I can use the invocation to open the skill and get the proper intro and help text from alexa: "To use this skill please say..." However if i do that i get a "turn off" chime and nothing happens. I also saw that voiceflow looks completely different from the video or your blog posts. That makes it hard to try and debug what's happening. For example i have no sidebar icons like blocks and stuff. See below picture vs. [the one on your blog](https://1.bp.blogspot.com/-XcdH2a_ActI/Xjxy6pOUXmI/AAAAAAAAAEo/ZJjwTwclm-05PDQGyyBJpicVVSrPNGDfgCNcBGAsYHQ/s1600/2020-02-06%2B%25283%2529.png) 

Any help or comment appreciated. Thanks for your work and the detailed documentation.

![image](https://user-images.githubusercontent.com/7281606/81384312-c2639880-9111-11ea-91c4-dd8a7f6328bb.png)

**Comment by andrewstech** [comment]
Hi
I hope to make a video about the new updated look of the skill soon.

The menu on the left if you click on steps then you can place new blocks.
Or on the flow menu this is where the code is divided into sections.
Region is where the skill intent is located and ENGLISH is where the
majority of the code to play the video is located.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by narfel** [comment]
Ah got it. Any ideas on the "turn off" chime? Is this the default action when alexa doesn't understand me? Or is it a language setting (mine is german). I'm not sure what happens to different language skills. She pronounces the sentences correctly, though.

**Comment by andrewstech** [comment]
Sorry I have no ideas. The chime is by Alexa not the skill.

**Comment by rajveer619** [comment]
Hey Andrew ! Thank you for creating this. Sadly whenever I say my invocation, Spoitify loads up the radio of the artist or the song. Could you guide me to help me figure out ?

**Comment by andrewstech** [comment]
May I ask what are you saying to start the skill?

**Comment by rajveer619** [comment]
Hey Alexa , ask fun time to play lucid dreams

**Comment by rajveer619** [comment]
Just to add on I've got a echo dot 3. I've installed the skilled thrice but I haven't got YouTube to work once. Not sure what I am doing wrong or missing

**Comment by andrewstech** [comment]
The only thing I can think off is that the alexa is not recognizing fun time If I were you I would try a different name.

**Comment by rajveer619** [comment]
Jeez I am really not sure what I am doing wrong... Does this have anything
to do with profiles ? Because I have 2

**Comment by andrewstech** [comment]
It should't as i have a few on mine. I would try heading over to your voiceflow project changing the name and click the upload button agin

**Comment by rajveer619** [comment]
I have done that a few times. Can I send you a youtube link to show you
what's up ? Maybe I can record myself speaking to alexa and then you could
perhaps assist me.

I am so sorry for using your time...

**Comment by andrewstech** [comment]
Yes feel free to send me a video as it might help me fix your problem.

**Comment by rajveer619** [comment]
https://youtu.be/tQJbrz6jLlY

It's a Private link so have a look. It keeps playing Spotify instead.

**Comment by andrewstech** [comment]
The video is private so I can't view it. If you change it to unlisted then
I should be able to view it.

**Comment by rajveer619** [comment]
There you go, it should be unlisted

**Comment by rajveer619** [comment]
Hi there , where you able to have a look at it?

**Comment by andrewstech** [comment]
Sorry for the wait. Do you know when you installed the skill?

**Comment by rajveer619** [comment]
Hi there,

I installed it recently after v3 was released. I am wondering if it could
be because my language was set to English UK previously.

**Comment by andrewstech** [comment]
It might be still not sure whats causing this issue.
