### ISSUE TITLE
Auto Screen detection not working??

### ISSUE THREAD

**Issue by BigVinny1983** [andrewstech/youtube-alexa-edition#13]
Hi Andrew

i use an amazon Echo for this skill but when i choose my song i get an error saying auto screen detection not working. i assume the is not intended to happen with the Dot is there a way around this?

**Comment by andrewstech** [comment]
I am looking into this now for you.

**Comment by andrewstech** [comment]
I am looking into this now for you.

**Comment by BigVinny1983** [comment]
Awesome thank you

**Comment by norfolk-lad** [comment]
Hi Andrew
Really interested in this you tube work around. However I get the auto screen detection not working problem and just one video playing but unable to get any more when asking for next.

**Comment by andrewstech** [comment]
Hi I am still looking into this I have contacted Voiceflow about the screen detection but as its the weekend they are closed. I will update this when I get a response.

**Comment by norfolk-lad** [comment]
Thanks - much appreciated.

**Comment by andrewstech** [comment]
Voiceflow is still looking into this as it's their code that tells the skill if the device has a screen

**Comment by norfolk-lad** [comment]
Many thanks Andrew for update - much appreciated. Philip.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BigVinny1983** [comment]
Thanks for the update

**Comment by andrewstech** [comment]
I have made a temporary fix as Voiceflow have yet to reply.
https://skills.andrewstech.me/youtube-alexa-edition-auto-screen-detection-broken/

**Comment by KillFacePT** [comment]
hello @andrewstech i've updated to the no detetion version, but im still getting: sorry something gonne wrong

**Comment by KillFacePT** [comment]
i've made a minor change to see where it comes from and its from youtube dl api

**Comment by KillFacePT** [comment]
Forget about it i've done a mistake on heroku setting

**Comment by andrewstech** [comment]
OK glad you found the issue

**Comment by andrewstech** [comment]
Hope that helps if I ever get the auto screen detection working again I will merge it in.

**Comment by BigVinny1983** [comment]
Thank you andrew i will try this tomorrow :0)

**Comment by BigVinny1983** [comment]
Couldnt wait till tomorrow so updated voice flow but now when i say the command instead of the screen detection error i just get sorry something has gone wrong!

**Comment by BigVinny1983** [comment]
Please ignore me all working now. Recreated my heroku skill and now all good

**Comment by andrewstech** [comment]
I will have a look

**Comment by norfolk-lad** [comment]
Hi Andrew. Working now as far as playing something from a selected artist but still not able to say next to move on to next video or song. The temporary fix got rid of the 'auto screen detection not working' error. Thank you.

**Comment by andrewstech** [comment]
Good to hear. Still not sure why it dosn't work if you say next but I will look into it
