### ISSUE TITLE
Sorry something has gone wrong

### ISSUE THREAD

**Issue by ilaurenc** [andrewstech/youtube-alexa-edition#16]
This may be an issue with my Google API setup more than a bug. The skill worked brilliantly for one day but now, any attempt to play returns "Loading Playing....Sorry something has gone wrong".

As part of my troubleshooting, I learned that if If I go to  https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=20&q=u2&type=video&key=APIkey in a browser, it returns a message "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e." 

If I go to the URL a couple more times, I get "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT)".

This is the first time I am using it for the day. I have checked the Google API setup and can find nothing wrong. One thing I note is that the Quotas page in Google Cloud Platform>IAM And Admin is showing my Current Usage under Queries per Day as 10,002. My limit is 10,000. It seems to be pushing me to 10,000 as soon as I try it once then failing because I am at my quota. 

Any thoughts on how to resolve this?

Regards,
Ian

**Comment by andrewstech** [comment]
Its sounds like your api key might be the same as someone else's. I would go to the credentials page on google APIs delete the key and generate a new key

**Comment by ilaurenc** [comment]
I tried that but no change. I then recreated the entire skill (all pieces of the puzzle including Heroku, Google, Voiceflow) and I am now experiencing issue #17.

**Comment by andrewstech** [comment]
I have made an update which should hopefully fix this issue.
