### ISSUE TITLE
Error with youtube api

### ISSUE THREAD

**Issue by djstar25** [andrewstech/youtube-alexa-edition#17]
I followed the guide by paul, but when ever i try to use it i get an error, i say alexa open youtube and it starts explaining how to use the app. then i say "alexa ask youtube to play (artist) and it waits a second and says loading playing (artist)... error communicating with youtube api.

i went and changed my api key hoping that would fix it but that didnt work. 
do you have any idea on how to fix this?

**Comment by iamyogeshg** [comment]
+1
I am facing exactly same error, I could see in google dashboard that there are lot of errors.

**Comment by andrewstech** [comment]
Have you used the skill before you started getting these errors.

**Comment by chinouvm** [comment]
> I followed the guide by paul, but when ever i try to use it i get an error, i say alexa open youtube and it starts explaining how to use the app. then i say "alexa ask youtube to play (artist) and it waits a second and says loading playing (artist)... error communicating with youtube api.
> 
> i went and changed my api key hoping that would fix it but that didnt work.
> do you have any idea on how to fix this?

+1

I did everything right but I just keeps saying error, even after trying new API keys

**Comment by djstar25** [comment]
> Have you used the skill before you started getting these errors.

Nope first time trying to use it

**Comment by andrewstech** [comment]
I have updated the skill which will hopefully fix this issue. Please update the skill on your side to get the new fix.

**Comment by stavroslab** [comment]
i just update the skill and just saying" loading play greenday" and nothing happened!

**Comment by chinouvm** [comment]
After the update, the error is gone but now it just doesn't play anything...

**Comment by andrewstech** [comment]
Found whats causing this new problem. The old issue has been fixed but the api the skill uses to check if a video is playable is down for maintenance.  I will see if I can make my own api as a backup as we don't yet know how long it will be down.

**Comment by andrewstech** [comment]
Update again switched to backup api. All should now be working.

**Comment by djstar25** [comment]
Will I need to change anything or should it just worknow?

**Comment by andrewstech** [comment]
You will need to update the skill. Sorry

**Comment by djstar25** [comment]
sorry this is my first time doing anything like this how do i update it 😅

**Comment by iamyogeshg** [comment]
> sorry this is my first time doing anything like this how do i update it 😅

Follow instructions from here:
https://www.youtube.com/watch?v=5k9OGbeek28&t=620s

**Comment by nathanfrindt** [comment]
Hi Andrew thanks for creating this project. I have followed your tutorial and Pauls on youtube was able to follow all the steps and it still seems to not be working correctly. When I try and test the skill it says "loading, playing 0, welcome to the Youtube Alexa skill, to use this skill please say. Alexa ask your skill name to play song name, For example Andrews invocation name is my music so Andrew would say "Alexa ask my music to play greedway" then the skill interaction ends. Is there another more recent update which is different than the v3 link you provided in the tutorial any help or advice would be greatly appreciated thanks man!

**Comment by andrewstech** [comment]
Hi

There is currently only one download link which changes to the latest
download link.

As for the skill you now open it by asking. For example my invocation name
is my music so I would say Alexa ask my music to play green day.


Where I have put my music that is invocation name that you have chosen for
the skill.

Hope this helps.

**Comment by ilaurenc** [comment]
I upgraded the skill and it worked brilliantly for 1 video. Now it just says "Loadingplaying Greenday" but nothing plays.

**Comment by djstar25** [comment]
+1 ^ same issue

**Comment by nathanfrindt** [comment]
Thanks Andrew I was able to get it to work! For anyone else having the issue you need to say “Alexa ask {your skills invocation name} to play {video you wish to listen to}. The skill with then say “loading playing {video you said}” and the video will start playing. The skill won’t work if you say “open {invocation name} or start {invocation name}.

**Comment by andrewstech** [comment]
@nathanfrindt Great

**Comment by kaplun22** [comment]
> I upgraded the skill and it worked brilliantly for 1 video. Now it just says "Loadingplaying Greenday" but nothing plays.

Faced same issue , have just installed the skill , it says 'Loadingplaying songname' after that there is silence

**Comment by tailsanj** [comment]
Hi Andrew, just need your help.  This skill was working for me yesterday but not today.  I have gone through all the steps again from Paul Hibberts video but all I now get is silence after I have given my alexa the voice command.  Any assistance would be much appreciated.

**Comment by markh1979** [comment]
I uploaded the skill and when I say "Alexa ask my music to play green day" it just says "Loadingplaying Greenday" but nothing plays.
i have the invocation name as "my music"

**Comment by andrewstech** [comment]
Sorry all I've been without internet for the past 2 days. I believe that I have found the issue. I will give you a update soon.

**Comment by andrewstech** [comment]
Unfortunately This is due to the third party api we use being down again. I am looking for solutions to this problem.

**Comment by andrewstech** [comment]
Forgot to mention this project has a status page. https://skills-status.andrewstech.me/

**Comment by andrewstech** [comment]
Sorry the bot seems to have closed all issues. I am manually reopening then.

**Comment by slopedog** [comment]
If this problem only applies to videos, is there a hack you can recommend that avoids that code path so that Echo devices can still play YouTube music?

**Comment by andrewstech** [comment]
Unfortunately the skill requires the URL checker functionality  ad YouTube
blocks certain videos. The music on standard echo's also requires this
feature. I am currently looking on ways to fix the skill.

**Comment by richaardvark** [comment]
I have the newest version from VoiceFlow and have filled in my Heroku link, my Google/YouTube API Key, and my two letter country code (US).  I also updated the invocation name, then it successfully uploaded the skill to my Alexa Developer Console.

However, it is still not working.  It says "You have hit your api usage try again tommorow" (spelled incorrectly).  I don't know how I have hit my API usage-limit if I've never once been able to successfully play a song... 🤔🙁

**Comment by tailsanj** [comment]
Hi Andrew, I also now have the newest version on VoiceFlow.  I created a new Heroku link and new API key and my two letter country code was already populated with GB. Upload was successful.  However, it is still not working. It says "Sorry, something went wrong".  I updated Voiceflow with the original Heroku link and API key that previously did work for me and I get the same "Sorry, something went wrong" response from my Alexa.  Any guidance will be much appreciated.

**Comment by andrewstech** [comment]
Hi all as for the Api that I have no idea why it get used so quickly.  When you get the error "you have hit your api usage" This is caused when the api responds with the error pictured bellow.
<img width="960" alt="fail api" src="https://user-images.githubusercontent.com/45342431/84380960-2cbf9b00-abe0-11ea-8f4a-c1e6620cc067.png">

As for the skill not responding I forgot to link one of the blocks and should be working now

**Comment by kenfabio** [comment]
Hi, I did everything from start and when I'm testing in Alexa console the message **"Welcome to youtubeloadingplaying ze ramalho Error talking to heroku. please check your link is correct."** appears, I copy and paste the link from heroku and not working. I translated "to play" "play" to "tocar" "toque" giving the comand "Alexa peça ao youtube para tocar ze ramalho" in pt-BR. Can you help

**Comment by andrewstech** [comment]
I would try resetting your heroku link.

**Comment by GhostChiller** [comment]
Hey andrewstech, I'm from germany. Your status website says that the YouTube API is disrupted.

I tried your skill on my amazon echo (german edition) but it doesn't work.

It always open the skill with the standard message
"Welcome to youtubeloadingplaying {Search_Query} Welcome to YouTube alexa editionTo use this skill please say. Alexa ask your skill name to play songname For example andrews invocation name is "my music" so andrew would say "alexa ask my music to play greenday""

Often it doesn't even respond to what I'm saying :|

I hope you'll get that fixed, I believe in you! 

Greetings from Germany, keep doing that brilliant work
