### ISSUE TITLE
Does this work with Alexa Spain?

### ISSUE THREAD

**Issue by Brokemboy** [andrewstech/youtube-alexa-edition#20]
So, I did it, I install this but Alexa speak in English and because I have Alexa in Spanish I did not understand her, so, there is a version of this in spanish?

Also, thanks for this, it is very useful. :D

**Comment by andrewstech** [comment]
Unfortunately no not at the moment. I am currently focusing on making the
skill more stable.

**Comment by Brokemboy** [comment]
Oh, got it, thanks for the answer ^^ but then, there is a way for me to translate it? I do not know about programing but I do know about english and spanish. :D

**Comment by andrewstech** [comment]
It should be as easily as changing the text in the speech box's but I will do some more research as we have attempted to translate it to German but that didn't seem to work. #15

**Comment by Brokemboy** [comment]
Okay, thanks for it, if you need help with the spanish translate I can help, I am not a translator but I know both languages. c:

**Comment by andrewstech** [comment]
Currently the skill is broken. Once we get it fixed then I will help with this.

Sorry for any inconveniences
Andrew
