### ISSUE TITLE
search for videos to play not songs

### ISSUE THREAD

**Issue by lurechasers** [andrewstech/youtube-alexa-edition#21]
Andrew where is the Voiceflow project download link to the YouTube Video skill that searches by Title to play "videos".  I'm not looking for the skill version that plays songs.    Thank you kind sir. Joel

**Comment by andrewstech** [comment]
Hi the download link is: https://download.andrewstech.me/youtube-skill-v3

The instruction's can be found here: https://skills.andrewstech.me/youtube-alexa-edition-setup/
