### ISSUE TITLE
Voiceflow not working

### ISSUE THREAD

**Issue by gb8may** [andrewstech/youtube-alexa-edition#29]
**Describe the bug**
The voiceflow on link https://download.andrewstech.me/youtube-skill-v3 is not the same of the tutorial. It's finishing after the example on how to ask to play

**To Reproduce**
1. Go to 'voiceflow dash board'
2. Click on 'Prototipe' then Start Test
3. See error after 'To use this skill please say. <prosody rate="medium">  Alexa ask your skill name to play songname</prosody> <break time="2s" />For example andrews invocation name is "my music" so andrew would say "alexa ask my music to play greenday"'

**Expected behavior**
Wait for my voice to ask a song.

**Screenshots**
![image](https://user-images.githubusercontent.com/35708820/84930791-36e20d80-b0a8-11ea-81a8-dc04f37d9df5.png)

**Comment by andrewstech** [comment]
Hi there the skill was updated on the 7th of may to fix many bugs. This changed the way we use the skill. Now we use the ask skill method as its more reliable. To use the skill say Alexa ask (your invocation name) to play (songname).  My invocation name is my music, so if I wanted to play greenday I would say  Alexa ask my music to play greenday.

**Comment by andrewstech** [comment]
As always the statues of the skill can be found on our status page.

https://skills-status.andrewstech.me/
