### ISSUE TITLE
Alexa says an error occurred if i want that Alexa plays YouTube Music.

### ISSUE THREAD

**Issue by realSnosh** [andrewstech/youtube-alexa-edition#3]
**Describe the bug**
Alexa says an error occurred if i want that Alexa plays YouTube Music.
**To Reproduce**
1. Say invocation name and the Video
2. See error

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS: Andorid 9
 - Browser Samsung Internet
 - Version /

**Additional context**
My Skill is uploaded to Alexa, and Alexa is reacting on my invoaction name.

**Comment by andrewstech** [comment]
We are working on a fix for the skill as lots of people are experiencing this bug.

**Comment by andrewstech** [comment]
Thanks this is now integrated and is working a treat. The new version is now published
