### ISSUE TITLE
YouTube API Usage | "You have hit your API usage, try again tomorrow"

### ISSUE THREAD

**Issue by GhostChiller** [andrewstech/youtube-alexa-edition#30]
**Describe the bug**
I updated the project and tried to play greenday but it doesn't work
it only respond with:
"Welcome to Youtube, loading playing greenday"
"You have hit your API usage, try again tomorrow"

**To Reproduce**
1. Say "Alexa ask [your innovation name] to play greenday"

-- ECHO DOT 3

**Comment by andrewstech** [comment]
This is an issue with the youtube Api. I am currently having a look at an unofficial Api which willl fix these issues.
I will update the status page with this issue.

https://skills-status.andrewstech.me/

**Comment by GhostChiller** [comment]
Ok, thank ya!

Wish you the best
