### ISSUE TITLE
It just loads the song and says playback stopped

### ISSUE THREAD

**Issue by Sangoku** [andrewstech/youtube-alexa-edition#4]
Skill works fine and all  but when it asks me to what sound to play and i say it it just loads the song and says playback stopped. cant get it to play.
How can i provide details to my setup or how can i help?

**Comment by andrewstech** [comment]
Hi sorry for the late reply unfortunately this is a bug that lots of people are experiencing. Fortunately I believe that we have found a fix.

**Comment by andrewstech** [comment]
This bug has now been fixed. Please update the skill.

Update method: https://youtu.be/5k9OGbeek28?t=598
