### ISSUE TITLE
There was a problem with requested skill response ...

### ISSUE THREAD

**Issue by Susja** [andrewstech/youtube-alexa-edition#5]
**Describe the bug**
Every time I try to invoke the skill I've got the message:
There was a problem with requested skill response ...

**To Reproduce**
1. Go to Alexa on my iPhone or Echo Dot
2. Click on Alexa icon or voice call Alexa to Echo Dot
3. You could here the voice message
4. See error on the iPhone screen:
Skill response was marked as failure
Request Identifier: amzn1....
The target Lambda application returned a failure response

**Expected behavior**
I expect that it start the skill
**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 14.x

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 14

**Additional context**

**Comment by andrewstech** [comment]
Is this for the up-to-date skill or the old one as I have noticed that your
error message talks about a lambda project.which this skill is not build
with.

**Comment by Susja** [comment]
Hi andrewstech
I installed 2 Skills: 'Google assistant' and 'YouTube' by using lambda. The current one I followed your instructions from this link  https://blog.andrewstech.me/p/youtube.html . It did not use lambda but when I invoke any of these Skill I’ve got exact same response “ The target Lambda application returned a failure response”
Nothing is working for me. 
Thanks

**Comment by andrewstech** [comment]
Make sure that the old and new skills don't share the same name. Then head to voiceflow and click on the upload to Alexa button again.  It sounds like voiceflow may of crashed when uploading the skill.

**Comment by Susja** [comment]
I double-checked that each skill has it's own distinctive name.
I uploaded voiceflow to Alexa again.
I've got exact same error messge.

**Comment by andrewstech** [comment]
Hi a update was released for the skill about 11 days ago which may fix this issue.
Also I strongly recommend that you watch the tutorial video by Paul Hibbert if you haven't already. 
https://youtu.be/5k9OGbeek28

**Comment by andrewstech** [comment]
let me know if your still having issues.
