### ISSUE TITLE
Certain videos will not play and cause the skill to hang

### ISSUE THREAD

**Issue by mcjoshea** [andrewstech/youtube-alexa-edition#6]
**Describe the bug**
When the following command is run in the skill: 
{dl_sever}/api/info?url=https://www.youtube.com/watch?v={search_id} 
sometimes the resulting link returned for a particular video will not work.
Here is an example error when a problem URL is opened in a browser: 
Access to r1---sn-q0cedn7s.googlevideo.com was denied. You don't have authorisation to view this page. HTTP ERROR 403

**To Reproduce**
1. Ask Alexa to play; "The banks of my own lovely lee"
2. One of the results returned will have this videoId: 6w5N6wqhCuU
3. The youtube-dl-api-server then returns with a number of different media links  but when checked manually none of them work. They all give the above error message.
4. There seems to be no way to check for such errors in VoiceFlow so when the faulty URL is passed to the Stream function, the skill just hangs.

**Expected behavior**
The link returned by the youtube-dl-api-server should be correct and if it was the skill would not hang.

**Desktop (please complete the following information):**
This has been tested in the Prototype area of VoiceFlow on a desktop running Chrome and with an Echo and Echo Dot device.

**Additional context**
I have a feeling that the issue may be due to a configuration issue with the youtube-dl-api-server. I can play the same video successfully using NewPipe on my phone but oddly not with invidio.us 
Even if the bad URLs issue can't be resolved, maybe some better error checking could be created so the stream function could just skip any blocked URLs.

**Comment by andrewstech** [comment]
I believe that we have found a new way to fix this issue. Please check  #8  this will be integrated into the next update.

**Comment by andrewstech** [comment]
Skill updated this is now fixed.

Update method:  https://youtu.be/5k9OGbeek28?t=598
