### ISSUE TITLE
Alexa - Protocol Violation

### ISSUE THREAD

**Issue by SwiftlyDesign** [andrewstech/youtube-alexa-edition#7]
I try and request a song on the skill and the Alexa app gives me this response

----
YouTube Skill V3
Request Identifier: amzn1.echo-api.request.407f4e54-a01b-4e57-b09c-9808c4aff740

The application response did not conform to the specification. Please ensure that you are using the latest client library and that your responses comply with the Application Service Interface.
----

**Comment by andrewstech** [comment]
This is a bug with Voiceflow. To solve go back to your voiceflow project and click the upload to Alexa button again.
