### ISSUE TITLE
URL error checking error

### ISSUE THREAD

**Issue by mcjoshea** [andrewstech/youtube-alexa-edition#8]
**Describe the bug**
Your Voiceflow project currently checks for blocked URLs by looking for the "_src property must be a valid json object_" result from a GET request to the media's URL. This unfortunately gives the same result for both _working_ and _blocked_  video URLs.

**To Reproduce**
Try these two video codes to pull down a test URL from a youtube dl api server:

1. Working video ID: [n-i8ljrcu8w](https://www.youtube.com/watch?v=n-i8ljrcu8w)
2. Blocked video ID: [6w5N6wqhCuU](https://www.youtube.com/watch?v=6w5N6wqhCuU)

The video URLs, that are extracted from these two video IDs, when fed through your error checking module, return the _same_ JSON result: "src property must be a valid json object".

**Expected behavior**
To do a successful error check, different results should be returned depending upon whether the tested URL is either working or blocked.

**Possible solution**
Use an API to check the URL. 
Here are some that could be used:
https://helloacm.com/tools/can-visit/

To see what this does you can simply click on these two API tests. The first is for a working URL and the second is for a blocked URL: 

1. https://uploadbeta.com/api/can-visit/?url=http://www.google.co.uk
2. [https://uploadbeta.com/api/can-visit/?url=https://r1---sn-u5a3u5a3-aigz.googlevideo.com/videoplayback?](https://uploadbeta.com/api/can-visit/?url=https://r1---sn-u5a3u5a3-aigz.googlevideo.com/videoplayback?)

Ideally the API server, used for the URL checking, should be based in the same region as the playback device, due to YouTube's geoblocking.

Here is an example of a Voiceflow API block that should work in your project:

> Request URL
> POST: https://uploadbeta.com/api/can-visit/
> 
> Parameter Assignments
> url
> 
> Body 
> URL Encoded
> 
> Transform into Variables
> response.code

If response.code=200 then you have a good URL.

**Comment by andrewstech** [comment]
Thankyou for pointing this out to me. I will get this integrated in the next update.

**Comment by andrewstech** [comment]
Thanks this is now integrated and makes the skill so much more stable. This is now in the published version.
