### ISSUE TITLE
Device ROAV VIVA does not play song

### ISSUE THREAD

**Issue by SwiftlyDesign** [andrewstech/youtube-alexa-edition#9]
**Describe the bug**

**To Reproduce**
Using a ROAV VIVA (Third party alexa device for car) the skill will activate as normal but when the skill gets to the playing the song (Streaming) part there is no song playing.
I also get no errors.
I have updated to the new code I have had this issue on the old and new code
I am happy to send video evidence if needed

**Expected behavior**
Expect it to play the song :/

**Screenshots**

**Comment by andrewstech** [comment]
I am having to do some research on this but best guess is that the roav
viva may use a different method of playing music.

**Comment by SwiftlyDesign** [comment]
Would you like me to test anything or any ideas to try help fix the issue

**Comment by andrewstech** [comment]
Unfortunately it appears that Roav uses a custom audio player. This means that its not compatible. sorry

**Comment by SwiftlyDesign** [comment]
Not to worry is there anyway to get the old YouTube Alexa to work? That usto work on the Roav Viva

**Comment by andrewstech** [comment]
The old skill should still work. :
https://www.youtube.com/watch?v=mluD8kQ06NM

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by SwiftlyDesign** [comment]
I have updated all the code now and get there was a problem with the requested skills response

**Comment by SwiftlyDesign** [comment]
It will say. Welcome to youtube, say for example play videos by the Beatles 

But when I ask for a song then it will fail
